language: cpp
sudo: required
compiler:
- clang
- gcc
os:
- linux
- osx
before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install liblapack-dev && sudo apt-get install libblas-dev && sudo apt-get install libsuperlu-dev; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew install homebrew/science/superlu; fi
- echo $LANG
- echo $LC_ALL
- mkdir build && cd build && cmake ..
script:
- make
